### ISSUE TITLE
VS + Flask

### ISSUE THREAD

**Issue by Fede-A-5I** [PioIX/G14_TPIF_C2#8]
buscar la forma para tener Flask en VS para asi no tener que crear mas de 1 repositorio

**Comment by Fede-A-5I** [comment]
https://youtu.be/GHvj1ivQ7ms

**Comment by Fede-A-5I** [comment]
https://code.visualstudio.com/docs/python/tutorial-flask

**Comment by Fvazquez-pioix** [comment]
hagan los 2 repos es mas rapido y menos complicado
